In [5]:
# for HeartDisease.csv

from google.colab import drive

drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [6]:
import pandas as pd

df=pd.read_csv('/content/drive/MyDrive/0.MKCE/4.Decision Tree/2 Project/Heart Disease Prediction/Dataset/HeartDisease.csv')

In [7]:
df

,age,gender,chest_pain,rest_bps,cholestrol,fasting_blood_sugar,rest_ecg,thalach,exer_angina,old_peak,slope,ca,thalassemia,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [43]:
x = df.drop(['target'],axis=1)
y = df['target']
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   age                  303 non-null    int64
 1   gender               303 non-null    int64
 2   chest_pain           303 non-null    int64
 3   rest_bps             303 non-null    int64
 4   cholestrol           303 non-null    int64
 5   fasting_blood_sugar  303 non-null    int64
 6   rest_ecg             303 non-null    int64
 7   thalach              303 non-null    int64
 8   exer_angina          303 non-null    int64
 9   old_peak             303 non-null    float64
 10  slope                303 non-null    int64
 11  ca                   303 non-null    int64
 12  thalassemia          303 non-null    int64
dtypes: float64(1), int64(12)
memory usage: 30.9 KB

In [37]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.26,random_state=0)

In [38]:
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier()

model.fit(xtrain,ytrain)

DecisionTreeClassifier()

In [39]:
ypred = model.predict(xtest)

In [40]:
# measuring the accuracy of model

from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

accuracy_score(ytest,ypred)

0.810126582278481

In [41]:
confusion_matrix(ytest,ypred)

array([[28,  7],
       [ 8, 36]])

In [42]:
print(classification_report(ytest,ypred))

              precision    recall  f1-score   support

           0       0.78      0.80      0.79        35
           1       0.84      0.82      0.83        44

    accuracy                           0.81        79
   macro avg       0.81      0.81      0.81        79
weighted avg       0.81      0.81      0.81        79