In [ ]:
# for credit_card.csv

from google.colab import drive
drive.mount('/content/drive')

In [ ]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/0.MKCE/Datasets/credit_card.csv')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 32 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   OBS#              1000 non-null   int64
 1   CHK_ACCT          1000 non-null   int64
 2   DURATION          1000 non-null   int64
 3   HISTORY           1000 non-null   int64
 4   NEW_CAR           1000 non-null   int64
 5   USED_CAR          1000 non-null   int64
 6   FURNITURE         1000 non-null   int64
 7   RADIO/TV          1000 non-null   int64
 8   EDUCATION         1000 non-null   int64
 9   RETRAINING        1000 non-null   int64
 10  AMOUNT            1000 non-null   int64
 11  SAV_ACCT          1000 non-null   int64
 12  EMPLOYMENT        1000 non-null   int64
 13  INSTALL_RATE      1000 non-null   int64
 14  MALE_DIV          1000 non-null   int64
 15  MALE_SINGLE       1000 non-null   int64
 16  MALE_MAR_or_WID   1000 non-null   int64
 17  CO-APPLICANT      1000 non-null   int64
 18  GUARANTOR         1000 non-null   int64
 19  PRESENT_RESIDENT  1000 non-null   int64
 20  REAL_ESTATE       1000 non-null   int64
 21  PROP_UNKN_NONE    1000 non-null   int64
 22  AGE               1000 non-null   int64
 23  OTHER_INSTALL     1000 non-null   int64
 24  RENT              1000 non-null   int64
 25  OWN_RES           1000 non-null   int64
 26  NUM_CREDITS       1000 non-null   int64
 27  JOB               1000 non-null   int64
 28  NUM_DEPENDENTS    1000 non-null   int64
 29  TELEPHONE         1000 non-null   int64
 30  FOREIGN           1000 non-null   int64
 31  RESPONSE          1000 non-null   int64
dtypes: int64(32)
memory usage: 250.1 KB

In [ ]:
x = df.drop(['RESPONSE'],axis=1)
y = df['RESPONSE']
x.columns

Index(['OBS#', 'CHK_ACCT', 'DURATION', 'HISTORY', 'NEW_CAR', 'USED_CAR',
       'FURNITURE', 'RADIO/TV', 'EDUCATION', 'RETRAINING', 'AMOUNT',
       'SAV_ACCT', 'EMPLOYMENT', 'INSTALL_RATE', 'MALE_DIV', 'MALE_SINGLE',
       'MALE_MAR_or_WID', 'CO-APPLICANT', 'GUARANTOR', 'PRESENT_RESIDENT',
       'REAL_ESTATE', 'PROP_UNKN_NONE', 'AGE', 'OTHER_INSTALL', 'RENT',
       'OWN_RES', 'NUM_CREDITS', 'JOB', 'NUM_DEPENDENTS', 'TELEPHONE',
       'FOREIGN'],
      dtype='object')

In [ ]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2,random_state=0)

In [ ]:
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier()

model.fit(xtrain,ytrain)

xtrain.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 800 entries, 687 to 684
Data columns (total 31 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   OBS#              800 non-null    int64
 1   CHK_ACCT          800 non-null    int64
 2   DURATION          800 non-null    int64
 3   HISTORY           800 non-null    int64
 4   NEW_CAR           800 non-null    int64
 5   USED_CAR          800 non-null    int64
 6   FURNITURE         800 non-null    int64
 7   RADIO/TV          800 non-null    int64
 8   EDUCATION         800 non-null    int64
 9   RETRAINING        800 non-null    int64
 10  AMOUNT            800 non-null    int64
 11  SAV_ACCT          800 non-null    int64
 12  EMPLOYMENT        800 non-null    int64
 13  INSTALL_RATE      800 non-null    int64
 14  MALE_DIV          800 non-null    int64
 15  MALE_SINGLE       800 non-null    int64
 16  MALE_MAR_or_WID   800 non-null    int64
 17  CO-APPLICANT      800 non-null    int64
 18  GUARANTOR         800 non-null    int64
 19  PRESENT_RESIDENT  800 non-null    int64
 20  REAL_ESTATE       800 non-null    int64
 21  PROP_UNKN_NONE    800 non-null    int64
 22  AGE               800 non-null    int64
 23  OTHER_INSTALL     800 non-null    int64
 24  RENT              800 non-null    int64
 25  OWN_RES           800 non-null    int64
 26  NUM_CREDITS       800 non-null    int64
 27  JOB               800 non-null    int64
 28  NUM_DEPENDENTS    800 non-null    int64
 29  TELEPHONE         800 non-null    int64
 30  FOREIGN           800 non-null    int64
dtypes: int64(31)
memory usage: 200.0 KB

In [ ]:
ypred = model.predict(xtest)

In [ ]:
accuracy_score(ytest,ypred)

0.67

In [ ]:
confusion_matrix(ytest,ypred)

array([[ 26,  32],
       [ 34, 108]])

In [ ]:
print(classification_report(ytest,ypred))

              precision    recall  f1-score   support

           0       0.43      0.45      0.44        58
           1       0.77      0.76      0.77       142

    accuracy                           0.67       200
   macro avg       0.60      0.60      0.60       200
weighted avg       0.67      0.67      0.67       200

In [ ]:
help(DecisionTreeClassifier)